version: '3.8'

services:
  app:
    build: .
    environment:
      - SECRET_KEY=OfMuZxfGYLD8cZlQLUYZ2iLanBcLQipab3MYvxIVj5bbhlu6I9
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", ":8000", "--workers", "2", "first_website.wsgi"]
#     volumes:
#       - sqlite_data:/code/db

# volumes:
#   sqlite_data:
