# Generated by Django 3.2.22 on 2024-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20240413_1223'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user_in_app',
            name='backend_use_registe_913283_idx',
        ),
        migrations.AlterField(
            model_name='user_in_app',
            name='profile_picture_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['email', 'registered_date', 'username'], name='backend_use_email_bbc89d_idx'),
        ),
    ]
