# Generated by Django 3.2.22 on 2024-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240413_1228'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user_in_app',
            name='backend_use_email_v_53b634_idx',
        ),
        migrations.RemoveIndex(
            model_name='user_in_app',
            name='backend_use_otp_9b38c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='user_in_app',
            name='backend_use_profile_cb892d_idx',
        ),
        migrations.RemoveIndex(
            model_name='user_in_app',
            name='backend_use_email_bbc89d_idx',
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['email'], name='backend_use_email_1a83e5_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['username'], name='backend_use_usernam_04f960_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['registered_date'], name='backend_use_registe_736a15_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['verified_through_auth_provider'], name='backend_use_verifie_94859e_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['email_verified'], name='backend_use_email_v_d251ea_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['otp_created_at'], name='backend_use_otp_cre_39e606_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['otp'], name='backend_use_otp_18cb3c_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['profile_picture_url'], name='backend_use_profile_04faca_idx'),
        ),
        migrations.AddIndex(
            model_name='user_in_app',
            index=models.Index(fields=['password'], name='backend_use_passwor_38ef3f_idx'),
        ),
    ]
