# Generated by Django 3.2.22 on 2024-04-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_in_app_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs_from_django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_string', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
    ]
